<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <clear />
        <add key="github" value="https://nuget.pkg.github.com/francolenzo/index.json" />
    </packageSources>
    <packageSourceCredentials>
        <github>
            <add key="Username" value="francolenzo" />
            <add key="ClearTextPassword" value="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" />
        </github>
    </packageSourceCredentials>
</configuration>
